version: "3.7"

services: 
    webhook:
        build: ./
        image: webhook
        container_name: webhook
        networks: 
            - caddy
        restart: unless-stopped
        logging:
            driver: "json-file"
            options:
                max-size: "1m"
        tty: true
        env_file: 
            .env
        ports: 
            - 8000:80

networks: 
    caddy:
        external: true