version: "3.7"

services: 
    app:
        build: ./
        restart: unless-stopped
        logging:
            driver: "json-file"
            options:
                max-size: "1m"
        tty: true
        env_file: 
            .env
        ports: 
            - 8000:80

    test:
        image: ubuntu
        container_name: test
        logging:
            driver: "json-file"
            options:
                max-size: "1m"

